# Generated by Django 6.0 on 2026-01-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('cloth_type', models.CharField(choices=[('Shirt', 'Shirt'), ('Pant', 'Pant'), ('Bedsheet', 'Bedsheet')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('service_type', models.CharField(choices=[('Wash', 'Wash'), ('Wash & Iron', 'Wash & Iron')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Washing', 'Washing'), ('Ready', 'Ready'), ('Delivered', 'Delivered')], default='Pending', max_length=20)),
            ],
        ),
    ]
